<?= $this->extend('theme/template') ?>

<?= $this->section('content') ?>
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6"><h1 class="m-0">Reports</h1></div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="<?= base_url('dashboard') ?>">Home</a></li>
            <li class="breadcrumb-item active">Reports</li>
          </ol>
        </div>
      </div>
    </div>
  </div>

  <section class="content">
    <div class="container-fluid">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Generated Reports</h3>
          <div class="card-tools">
            <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#AddNewModal">
              <i class="fa fa-plus-circle fa-fw"></i> Generate New Report
            </button>
          </div>
        </div>
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped table-sm">
            <thead>
              <tr>
                <th>No.</th>
                <th style="display:none;">ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Period Start</th>
                <th>Period End</th>
                <th>Generated By</th>
                <th>Created At</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Generate Report Modal -->
    <div class="modal fade" id="AddNewModal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-lg" role="document">
        <form id="addReportForm">
          <?= csrf_field() ?>
          <div class="modal-content">
            <div class="modal-header bg-primary text-white">
              <h5 class="modal-title"><i class="fa fa-plus-circle fa-fw"></i> Generate New Report</h5>
              <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <label>Report Title <span class="text-danger">*</span></label>
                    <input type="text" name="title" class="form-control" required />
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label>Report Type <span class="text-danger">*</span></label>
                    <select name="report_type" class="form-control" required>
                      <option value="">Select Type</option>
                      <option value="Blotter">Blotter</option>
                      <option value="Clearance">Clearance</option>
                      <option value="Permit">Permit</option>
                      <option value="Demographic">Demographic</option>
                      <option value="Financial">Financial</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Period Start <span class="text-danger">*</span></label>
                    <input type="date" name="period_start" class="form-control" required />
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Period End <span class="text-danger">*</span></label>
                    <input type="date" name="period_end" class="form-control" required />
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-group">
                    <label>Description</label>
                    <textarea name="description" class="form-control" rows="3"></textarea>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancel</button>
              <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Generate</button>
            </div>
          </div>
        </form>
      </div>
    </div>

    <!-- Edit Report Modal -->
    <div class="modal fade" id="editReportModal" tabindex="-1" role="dialog">
      <div class="modal-dialog modal-lg" role="document">
        <form id="editReportForm">
          <?= csrf_field() ?>
          <div class="modal-content">
            <div class="modal-header bg-warning text-dark">
              <h5 class="modal-title"><i class="far fa-edit fa-fw"></i> Edit Report</h5>
              <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body">
              <input type="hidden" name="id" id="reportId">
              <div class="row">
                <div class="col-md-8">
                  <div class="form-group">
                    <label>Report Title <span class="text-danger">*</span></label>
                    <input type="text" name="title" id="editTitle" class="form-control" required />
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label>Report Type <span class="text-danger">*</span></label>
                    <select name="report_type" id="editReportType" class="form-control" required>
                      <option value="Blotter">Blotter</option>
                      <option value="Clearance">Clearance</option>
                      <option value="Permit">Permit</option>
                      <option value="Demographic">Demographic</option>
                      <option value="Financial">Financial</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Period Start <span class="text-danger">*</span></label>
                    <input type="date" name="period_start" id="editPeriodStart" class="form-control" required />
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Period End <span class="text-danger">*</span></label>
                    <input type="date" name="period_end" id="editPeriodEnd" class="form-control" required />
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-group">
                    <label>Description</label>
                    <textarea name="description" id="editDescription" class="form-control" rows="3"></textarea>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times-circle"></i> Cancel</button>
              <button type="submit" class="btn btn-warning"><i class="fa fa-save"></i> Update Report</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>

<div class="toasts-top-right fixed"></div>
<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script>const baseUrl = "<?= base_url() ?>";</script>
<script src="<?= base_url('public/js/reports/reports.js') ?>"></script>
<?= $this->endSection() ?>
